# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-05 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalshirts',
            name='avalable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formalshirts',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formalshirts',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
