# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-05 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0002_auto_20180705_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalshirts',
            name='photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
